### ISSUE TITLE
Newtonsoft.dll already part of Unity

### ISSUE THREAD

**Issue by JShull** [vmasc-capabilities-lab/RUDE#1]
Unity now includes the Newtonsoft.json.dll as an isolated package. I would consider referencing the dependency and not including the *.dll within your package.

In order for me to use your package I have to remove the Version Control package that Unity offers which has a dependency to Newtonsoft as well. 

![image](https://user-images.githubusercontent.com/12342337/145548383-4f97156c-aea4-45b7-92f7-d460ac820760.png)

**Comment by BrandonFeldhaus** [comment]
Thank you for submitting this issue.

You will find with the latest commit this has been resolved, RUDE no longer include the Newtonsoft.json.dll and references the Unity version.
