### ISSUE TITLE
Meta files missing

### ISSUE THREAD

**Issue by JShull** [vmasc-capabilities-lab/RUDE#2]
When generating the repository for the Package Manager - make sure you have your hidden meta files set to visible before you copy your files over to the package. In newer versions of Unity, Unity is looking for those meta files to be part of the package and thus throws an error for every missing meta file. This doesn't cause an issue from running/testing - but just a visual nightmare.

![image](https://user-images.githubusercontent.com/12342337/145550741-ef0a2fcb-8d61-43ef-bc04-26e302554646.png)

**Comment by BrandonFeldhaus** [comment]
Thank you for submitting this issue. 

After looking into this issue, these files were apart of our Github documentation for the package and should not be apart of the package itself. 

At this time, I have resolved the missing meta file issue and will look to removing the documentation files in the future.
